# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generates metrics reports containing 5-seconds sampled speed when an `event`
# is published. If adjacent events take place within a 5 seconds range, they
# are considered to be a 'series of events`.
# This configuration allows reporting speed aggregated over a period of
# 5 seconds after the series' first and last event occur, as well as speed
# aggregated over a period of 5 seconds before **any** event occurs.
#
# This configuration uses two sources for storing event timestamps. When a
# new event is published, it stores its timestamp along with previous event
# timestamp to be able to deterministally find which event is the first one for
# a series.

uuid: "1c1a37e5-f03b-4e6d-bef0-3b91db4d46f8"
version: 3758096386
descriptor_protos {
  name: "adhoc.proto"
  package: "aaos.sdv.telemetry.adhoc"
  message_type {
    name: "series_first_event_timestamp_publisher"
    field { name: "timestamp" number: 1 type: TYPE_INT64 }
  }
  message_type {
    name: "speed_vector_aggregator"
    field { name: "vector" number: 1 label: LABEL_REPEATED type: TYPE_INT32 }
  }
  message_type {
    name: "new_event_timestamp_publisher"
    field { name: "timestamp" number: 1 type: TYPE_INT64 }
  }
  message_type {
    name: "on_new_event_aggregator"
    field { name: "previous_event_timestamp" number: 1 type: TYPE_INT64 }
    field { name: "events_count" number: 2 type: TYPE_INT32 }
  }
  message_type {
    name: "after_series_first_event_collected_data"
    field { name: "speed_vector" number: 1 label: LABEL_REPEATED type: TYPE_INT32 }
  }
  message_type {
    name: "after_series_last_event_collected_data"
    field { name: "speed_vector" number: 1 label: LABEL_REPEATED type: TYPE_INT32 }
  }
  message_type {
    name: "before_event_collected_data"
    field { name: "speed_vector" number: 1 label: LABEL_REPEATED type: TYPE_INT32 }
  }
  syntax: "proto2"
}
triggers {
  name: "event_series_start_trigger"
  conditional_trigger {
    trigger_names: "new_event_timestamp_updated_trigger"
    selector_node_index: 8
    is_true {}
  }
}
triggers {
  name: "event_trigger"
  data_trigger { source_name: "event_publisher" }
}
triggers {
  name: "new_event_timestamp_updated_trigger"
  data_trigger { source_name: "new_event_timestamp_publisher" }
}
triggers {
  name: "on_event_processed_trigger"
  data_trigger { source_name: "on_new_event_aggregator" }
}
triggers {
  name: "on_series_first_event_timer_trigger"
  conditional_trigger {
    trigger_names: "periodic_400ms"
    selector_node_index: 14
    rising_edge {}
  }
}
triggers {
  name: "on_series_last_event_timer_trigger"
  conditional_trigger {
    trigger_names: "periodic_400ms"
    selector_node_index: 11
    rising_edge {}
  }
}
triggers {
  name: "periodic_1s"
  periodic_trigger { interval { seconds: 1 } }
}
triggers {
  name: "periodic_400ms"
  periodic_trigger { interval { nanos: 400000000 } }
}
sources {
  name: "series_first_event_timestamp_publisher"
  aggregator {
    trigger_names: "event_series_start_trigger"
    message_builder {
      message_type: ".aaos.sdv.telemetry.adhoc.series_first_event_timestamp_"
                    "publisher"
      field_assignments {
        field_name: "timestamp"
        no_aggregation { expression_node_index: 9 }
      }
    }
  }
}
sources {
  name: "speed_publisher"
  data_source {
    source_identifier: ".google.sdv.telemetry_samples.SpeedMsg"
    connection_type: SUBSCRIPTION
  }
}
sources {
  name: "speed_vector_aggregator"
  aggregator {
    trigger_names: "periodic_1s"
    message_builder {
      message_type: ".aaos.sdv.telemetry.adhoc.speed_vector_aggregator"
      field_assignments {
        field_name: "vector"
        vector_aggregation { expression_node_index: 15 max_length: 5 }
      }
    }
  }
}
sources {
  name: "event_publisher"
  data_source {
    source_identifier: ".google.sdv.telemetry_samples.EventMsg"
    connection_type: SUBSCRIPTION
  }
}
sources {
  name: "new_event_timestamp_publisher"
  aggregator {
    trigger_names: "on_event_processed_trigger"
    message_builder {
      message_type: ".aaos.sdv.telemetry.adhoc.new_event_timestamp_publisher"
      field_assignments {
        field_name: "timestamp"
        no_aggregation { expression_node_index: 9 }
      }
    }
  }
}
sources {
  name: "on_new_event_aggregator"
  aggregator {
    trigger_names: "event_trigger"
    message_builder {
      message_type: ".aaos.sdv.telemetry.adhoc.on_new_event_aggregator"
      field_assignments {
        field_name: "previous_event_timestamp"
        no_aggregation { expression_node_index: 3 }
      }
      field_assignments {
        field_name: "events_count"
        count_aggregation {}
      }
    }
  }
}
# Expression Node 0
expression_nodes {
  field_leaf_node { source_name: "on_new_event_aggregator" field_names: "events_count" }
}
# Expression Node 1
expression_nodes { constant_leaf_node { int32_value: 1 } }
# Expression Node 2
expression_nodes { combination_node { left_index: 0 right_index: 1 relational_operator: EQ } }
# Expression Node 3
expression_nodes {
  field_leaf_node { source_name: "new_event_timestamp_publisher" field_names: "timestamp" }
}
# Expression Node 4
expression_nodes {
  field_leaf_node { source_name: "on_new_event_aggregator" field_names: "previous_event_timestamp" }
}
# Expression Node 5
expression_nodes { combination_node { left_index: 3 right_index: 4 arithmetic_operator: SUBTRACT } }
# Expression Node 6
expression_nodes { constant_leaf_node { int32_value: 5000000 } }
# Expression Node 7
expression_nodes { combination_node { left_index: 5 right_index: 6 relational_operator: GT_OR_EQ } }
# Expression Node 8
expression_nodes { combination_node { left_index: 2 right_index: 7 logical_operator: OR } }
# Expression Node 9
expression_nodes {
  function_leaf_node { get_current_timestamp { time_source: MONOTONIC_TIME_SINCE_BOOT } }
}
# Expression Node 10
expression_nodes { combination_node { left_index: 9 right_index: 3 arithmetic_operator: SUBTRACT } }
# Expression Node 11
expression_nodes {
  combination_node { left_index: 10 right_index: 6 relational_operator: GT_OR_EQ }
}
# Expression Node 12
expression_nodes {
  field_leaf_node { source_name: "series_first_event_timestamp_publisher" field_names: "timestamp" }
}
# Expression Node 13
expression_nodes {
  combination_node { left_index: 9 right_index: 12 arithmetic_operator: SUBTRACT }
}
# Expression Node 14
expression_nodes {
  combination_node { left_index: 13 right_index: 6 relational_operator: GT_OR_EQ }
}
# Expression Node 15
expression_nodes { field_leaf_node { source_name: "speed_publisher" field_names: "speed" } }
# Expression Node 16
expression_nodes {
  field_leaf_node { source_name: "speed_vector_aggregator" field_names: "vector" }
}
metrics_report_configs {
  name: "after_series_first_event_collected_data"
  trigger_names: "on_series_first_event_timer_trigger"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.after_series_first_event_"
                  "collected_data"
    field_assignments {
      field_name: "speed_vector"
      no_aggregation { expression_node_index: 16 }
    }
  }
}
metrics_report_configs {
  name: "after_series_last_event_collected_data"
  trigger_names: "on_series_last_event_timer_trigger"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.after_series_last_event_"
                  "collected_data"
    field_assignments {
      field_name: "speed_vector"
      no_aggregation { expression_node_index: 16 }
    }
  }
}
metrics_report_configs {
  name: "before_event_collected_data"
  trigger_names: "event_trigger"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.before_event_collected_data"
    field_assignments {
      field_name: "speed_vector"
      no_aggregation { expression_node_index: 16 }
    }
  }
}
