# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

uuid: "666176b1-66d8-4064-afa6-6e004fc39fac"
version: 3758096386
descriptor_protos {
  name: "adhoc.proto"
  package: "aaos.sdv.telemetry.adhoc"
  message_type {
    name: "TirePressureReport"
    field { name: "tire_pressure_fl" number: 1 type: TYPE_UINT32 }
  }
  syntax: "proto2"
}
triggers {
  name: "dt_report_trigger"
  data_trigger { publisher_name: "dt_tire_pressure_fl_publisher" }
}
publishers {
  name: "dt_tire_pressure_fl_publisher"
  service_publisher {
    service_name: "com.sdv.google.sample.apex.provider.Provider#TirePressure|"
                  "com-sdv-google-sample-apex-provider-tire-pressure-front-"
                  "left"
    connection_type: SUBSCRIPTION
    sub_sampling_interval { seconds: 5 }
  }
}
# Expression Node 0
expression_nodes {
  field_leaf_node { publisher_name: "dt_tire_pressure_fl_publisher" field_names: "pressure" }
}
metrics_report_configs {
  name: "TirePressureReport"
  trigger_names: "dt_report_trigger"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.TirePressureReport"
    field_assignments {
      field_name: "tire_pressure_fl"
      no_aggregation { expression_node_index: 0 }
    }
  }
}
