# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

uuid: "f910f4ef-573f-40c6-b75e-289ce8f67b1d"
version: 3758096386
descriptor_protos {
  name: "adhoc.proto"
  package: "aaos.sdv.telemetry.adhoc"
  message_type {
    name: "aggregations"
    field { name: "integer_list" number: 1 label: LABEL_REPEATED type: TYPE_INT32 }
  }
  message_type {
    name: "boolean_report"
    field { name: "boolean" number: 1 type: TYPE_BOOL }
    field { name: "logical_not_true" number: 2 type: TYPE_BOOL }
    field { name: "logical_not_false" number: 3 type: TYPE_BOOL }
    field { name: "logical_and_true_true" number: 4 type: TYPE_BOOL }
    field { name: "logical_and_true_false" number: 5 type: TYPE_BOOL }
    field { name: "logical_and_false_true" number: 6 type: TYPE_BOOL }
    field { name: "logical_and_false_false" number: 7 type: TYPE_BOOL }
    field { name: "logical_or_true_true" number: 8 type: TYPE_BOOL }
    field { name: "logical_or_true_false" number: 9 type: TYPE_BOOL }
    field { name: "logical_or_false_true" number: 10 type: TYPE_BOOL }
    field { name: "logical_or_false_false" number: 11 type: TYPE_BOOL }
    field { name: "logical_xor_true_true" number: 12 type: TYPE_BOOL }
    field { name: "logical_xor_true_false" number: 13 type: TYPE_BOOL }
    field { name: "logical_xor_false_true" number: 14 type: TYPE_BOOL }
    field { name: "logical_xor_false_false" number: 15 type: TYPE_BOOL }
  }
  message_type {
    name: "float_report"
    field { name: "float" number: 1 type: TYPE_FLOAT }
    field { name: "rounding_floor" number: 2 type: TYPE_INT64 }
    field { name: "rounding_round" number: 3 type: TYPE_INT64 }
    field { name: "rounding_ceil" number: 4 type: TYPE_INT64 }
  }
  message_type {
    name: "integer_list_report"
    field { name: "integer_list" number: 1 label: LABEL_REPEATED type: TYPE_INT32 }
    field { name: "relational_contains_30" number: 2 type: TYPE_BOOL }
    field { name: "relational_contains_30_0" number: 3 type: TYPE_BOOL }
    field { name: "relational_contains_10" number: 4 type: TYPE_BOOL }
    field { name: "relational_does_not_contain" number: 5 type: TYPE_BOOL }
    field { name: "relational_all_equal_to" number: 6 type: TYPE_BOOL }
  }
  message_type {
    name: "integer_report"
    field { name: "integer" number: 1 type: TYPE_INT32 }
    field { name: "relational_equal" number: 2 type: TYPE_BOOL }
    field { name: "relational_not_equal" number: 3 type: TYPE_BOOL }
    field { name: "relational_greater_than" number: 4 type: TYPE_BOOL }
    field { name: "relational_greater_equal_than" number: 5 type: TYPE_BOOL }
    field { name: "relational_less_than" number: 6 type: TYPE_BOOL }
    field { name: "relational_less_equal_than" number: 7 type: TYPE_BOOL }
    field { name: "arithmetic_add" number: 8 type: TYPE_DOUBLE }
    field { name: "arithmetic_subtract" number: 9 type: TYPE_INT64 }
    field { name: "arithmetic_multiply" number: 10 type: TYPE_INT64 }
    field { name: "arithmetic_divide" number: 11 type: TYPE_DOUBLE }
    field { name: "arithmetic_unary_minus" number: 12 type: TYPE_INT64 }
    field { name: "arithmetic_modulo_trunc" number: 13 type: TYPE_INT64 }
    field { name: "arithmetic_modulo_trunc_negative" number: 14 type: TYPE_INT64 }
    field { name: "arithmetic_power_2" number: 15 type: TYPE_DOUBLE }
    field { name: "arithmetic_power_1_5" number: 16 type: TYPE_DOUBLE }
    field { name: "arithmetic_power_minus_1" number: 17 type: TYPE_DOUBLE }
    field { name: "arithmetic_absolute_positive" number: 18 type: TYPE_INT64 }
    field { name: "arithmetic_absolute_negative" number: 19 type: TYPE_INT64 }
  }
  syntax: "proto2"
}
triggers {
  name: "data_trigger"
  data_trigger { source_name: "data_publisher" }
}
triggers {
  name: "periodic_1s"
  periodic_trigger { interval { seconds: 1 } }
}
sources {
  name: "data_publisher"
  data_source {
    source_identifier: ".google.sdv.telemetry_samples.OperatorsTestdata"
    connection_type: SUBSCRIPTION
  }
}
sources {
  name: "aggregations"
  aggregator {
    trigger_names: "data_trigger"
    message_builder {
      message_type: ".aaos.sdv.telemetry.adhoc.aggregations"
      field_assignments {
        field_name: "integer_list"
        vector_aggregation { expression_node_index: 0 }
      }
    }
  }
}
# Expression Node 0
expression_nodes { field_leaf_node { source_name: "data_publisher" field_names: "integer" } }
# Expression Node 1
expression_nodes { constant_leaf_node { float_value: 30 } }
# Expression Node 2
expression_nodes { combination_node { left_index: 0 right_index: 1 relational_operator: EQ } }
# Expression Node 3
expression_nodes { constant_leaf_node { int32_value: 30 } }
# Expression Node 4
expression_nodes { combination_node { left_index: 0 right_index: 3 relational_operator: NOT_EQ } }
# Expression Node 5
expression_nodes { combination_node { left_index: 0 right_index: 3 relational_operator: GT } }
# Expression Node 6
expression_nodes { combination_node { left_index: 3 right_index: 0 relational_operator: GT_OR_EQ } }
# Expression Node 7
expression_nodes { combination_node { left_index: 0 right_index: 3 relational_operator: LT } }
# Expression Node 8
expression_nodes { combination_node { left_index: 0 right_index: 3 relational_operator: LT_OR_EQ } }
# Expression Node 9
expression_nodes { constant_leaf_node { float_value: 2.5 } }
# Expression Node 10
expression_nodes { combination_node { left_index: 0 right_index: 9 arithmetic_operator: ADD } }
# Expression Node 11
expression_nodes { constant_leaf_node { int32_value: 10 } }
# Expression Node 12
expression_nodes {
  combination_node { left_index: 11 right_index: 0 arithmetic_operator: SUBTRACT }
}
# Expression Node 13
expression_nodes { constant_leaf_node { int32_value: 7 } }
# Expression Node 14
expression_nodes {
  combination_node { left_index: 13 right_index: 0 arithmetic_operator: MULTIPLY }
}
# Expression Node 15
expression_nodes { constant_leaf_node { int32_value: 20 } }
# Expression Node 16
expression_nodes { combination_node { left_index: 0 right_index: 15 arithmetic_operator: DIVIDE } }
# Expression Node 17
expression_nodes { combination_node { left_index: 0 arithmetic_operator: UNARY_MINUS } }
# Expression Node 18
expression_nodes {
  combination_node { left_index: 0 right_index: 13 arithmetic_operator: MODULO_TRUNC }
}
# Expression Node 19
expression_nodes { constant_leaf_node { int32_value: -42 } }
# Expression Node 20
expression_nodes {
  combination_node { left_index: 19 right_index: 17 arithmetic_operator: MODULO_TRUNC }
}
# Expression Node 21
expression_nodes { constant_leaf_node { int32_value: 2 } }
# Expression Node 22
expression_nodes { combination_node { left_index: 0 right_index: 21 arithmetic_operator: POWER } }
# Expression Node 23
expression_nodes { constant_leaf_node { float_value: 1.5 } }
# Expression Node 24
expression_nodes { combination_node { left_index: 0 right_index: 23 arithmetic_operator: POWER } }
# Expression Node 25
expression_nodes { constant_leaf_node { int32_value: -1 } }
# Expression Node 26
expression_nodes { combination_node { left_index: 0 right_index: 25 arithmetic_operator: POWER } }
# Expression Node 27
expression_nodes { combination_node { left_index: 0 arithmetic_operator: ABSOLUTE } }
# Expression Node 28
expression_nodes { combination_node { left_index: 17 arithmetic_operator: ABSOLUTE } }
# Expression Node 29
expression_nodes { field_leaf_node { source_name: "aggregations" field_names: "integer_list" } }
# Expression Node 30
expression_nodes {
  combination_node { left_index: 29 right_index: 3 relational_operator: CONTAINS }
}
# Expression Node 31
expression_nodes {
  combination_node { left_index: 29 right_index: 1 relational_operator: CONTAINS }
}
# Expression Node 32
expression_nodes {
  combination_node { left_index: 29 right_index: 11 relational_operator: CONTAINS }
}
# Expression Node 33
expression_nodes {
  combination_node { left_index: 29 right_index: 3 relational_operator: DOES_NOT_CONTAIN }
}
# Expression Node 34
expression_nodes { combination_node { left_index: 29 right_index: 3 relational_operator: EQ } }
# Expression Node 35
expression_nodes { field_leaf_node { source_name: "data_publisher" field_names: "float" } }
# Expression Node 36
expression_nodes { combination_node { left_index: 35 rounding_operator: FLOOR } }
# Expression Node 37
expression_nodes { combination_node { left_index: 35 rounding_operator: ROUND } }
# Expression Node 38
expression_nodes { combination_node { left_index: 35 rounding_operator: CEIL } }
# Expression Node 39
expression_nodes { field_leaf_node { source_name: "data_publisher" field_names: "boolean" } }
# Expression Node 40
expression_nodes { combination_node { left_index: 39 logical_operator: NOT } }
# Expression Node 41
expression_nodes { combination_node { left_index: 40 logical_operator: NOT } }
# Expression Node 42
expression_nodes { combination_node { left_index: 39 right_index: 39 logical_operator: AND } }
# Expression Node 43
expression_nodes { combination_node { left_index: 39 right_index: 40 logical_operator: AND } }
# Expression Node 44
expression_nodes { combination_node { left_index: 40 right_index: 39 logical_operator: AND } }
# Expression Node 45
expression_nodes { combination_node { left_index: 40 right_index: 40 logical_operator: AND } }
# Expression Node 46
expression_nodes { combination_node { left_index: 39 right_index: 39 logical_operator: OR } }
# Expression Node 47
expression_nodes { combination_node { left_index: 39 right_index: 40 logical_operator: OR } }
# Expression Node 48
expression_nodes { combination_node { left_index: 40 right_index: 39 logical_operator: OR } }
# Expression Node 49
expression_nodes { combination_node { left_index: 40 right_index: 40 logical_operator: OR } }
# Expression Node 50
expression_nodes { combination_node { left_index: 39 right_index: 39 logical_operator: XOR } }
# Expression Node 51
expression_nodes { combination_node { left_index: 39 right_index: 40 logical_operator: XOR } }
# Expression Node 52
expression_nodes { combination_node { left_index: 40 right_index: 39 logical_operator: XOR } }
# Expression Node 53
expression_nodes { combination_node { left_index: 40 right_index: 40 logical_operator: XOR } }
metrics_report_configs {
  name: "boolean_report"
  trigger_names: "periodic_1s"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.boolean_report"
    field_assignments {
      field_name: "boolean"
      no_aggregation { expression_node_index: 39 }
    }
    field_assignments {
      field_name: "logical_not_true"
      no_aggregation { expression_node_index: 40 }
    }
    field_assignments {
      field_name: "logical_not_false"
      no_aggregation { expression_node_index: 41 }
    }
    field_assignments {
      field_name: "logical_and_true_true"
      no_aggregation { expression_node_index: 42 }
    }
    field_assignments {
      field_name: "logical_and_true_false"
      no_aggregation { expression_node_index: 43 }
    }
    field_assignments {
      field_name: "logical_and_false_true"
      no_aggregation { expression_node_index: 44 }
    }
    field_assignments {
      field_name: "logical_and_false_false"
      no_aggregation { expression_node_index: 45 }
    }
    field_assignments {
      field_name: "logical_or_true_true"
      no_aggregation { expression_node_index: 46 }
    }
    field_assignments {
      field_name: "logical_or_true_false"
      no_aggregation { expression_node_index: 47 }
    }
    field_assignments {
      field_name: "logical_or_false_true"
      no_aggregation { expression_node_index: 48 }
    }
    field_assignments {
      field_name: "logical_or_false_false"
      no_aggregation { expression_node_index: 49 }
    }
    field_assignments {
      field_name: "logical_xor_true_true"
      no_aggregation { expression_node_index: 50 }
    }
    field_assignments {
      field_name: "logical_xor_true_false"
      no_aggregation { expression_node_index: 51 }
    }
    field_assignments {
      field_name: "logical_xor_false_true"
      no_aggregation { expression_node_index: 52 }
    }
    field_assignments {
      field_name: "logical_xor_false_false"
      no_aggregation { expression_node_index: 53 }
    }
  }
}
metrics_report_configs {
  name: "float_report"
  trigger_names: "periodic_1s"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.float_report"
    field_assignments {
      field_name: "float"
      no_aggregation { expression_node_index: 35 }
    }
    field_assignments {
      field_name: "rounding_floor"
      no_aggregation { expression_node_index: 36 }
    }
    field_assignments {
      field_name: "rounding_round"
      no_aggregation { expression_node_index: 37 }
    }
    field_assignments {
      field_name: "rounding_ceil"
      no_aggregation { expression_node_index: 38 }
    }
  }
}
metrics_report_configs {
  name: "integer_list_report"
  trigger_names: "periodic_1s"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.integer_list_report"
    field_assignments {
      field_name: "integer_list"
      no_aggregation { expression_node_index: 29 }
    }
    field_assignments {
      field_name: "relational_contains_30"
      no_aggregation { expression_node_index: 30 }
    }
    field_assignments {
      field_name: "relational_contains_30_0"
      no_aggregation { expression_node_index: 31 }
    }
    field_assignments {
      field_name: "relational_contains_10"
      no_aggregation { expression_node_index: 32 }
    }
    field_assignments {
      field_name: "relational_does_not_contain"
      no_aggregation { expression_node_index: 33 }
    }
    field_assignments {
      field_name: "relational_all_equal_to"
      no_aggregation { expression_node_index: 34 }
    }
  }
}
metrics_report_configs {
  name: "integer_report"
  trigger_names: "periodic_1s"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.integer_report"
    field_assignments {
      field_name: "integer"
      no_aggregation { expression_node_index: 0 }
    }
    field_assignments {
      field_name: "relational_equal"
      no_aggregation { expression_node_index: 2 }
    }
    field_assignments {
      field_name: "relational_not_equal"
      no_aggregation { expression_node_index: 4 }
    }
    field_assignments {
      field_name: "relational_greater_than"
      no_aggregation { expression_node_index: 5 }
    }
    field_assignments {
      field_name: "relational_greater_equal_than"
      no_aggregation { expression_node_index: 6 }
    }
    field_assignments {
      field_name: "relational_less_than"
      no_aggregation { expression_node_index: 7 }
    }
    field_assignments {
      field_name: "relational_less_equal_than"
      no_aggregation { expression_node_index: 8 }
    }
    field_assignments {
      field_name: "arithmetic_add"
      no_aggregation { expression_node_index: 10 }
    }
    field_assignments {
      field_name: "arithmetic_subtract"
      no_aggregation { expression_node_index: 12 }
    }
    field_assignments {
      field_name: "arithmetic_multiply"
      no_aggregation { expression_node_index: 14 }
    }
    field_assignments {
      field_name: "arithmetic_divide"
      no_aggregation { expression_node_index: 16 }
    }
    field_assignments {
      field_name: "arithmetic_unary_minus"
      no_aggregation { expression_node_index: 17 }
    }
    field_assignments {
      field_name: "arithmetic_modulo_trunc"
      no_aggregation { expression_node_index: 18 }
    }
    field_assignments {
      field_name: "arithmetic_modulo_trunc_negative"
      no_aggregation { expression_node_index: 20 }
    }
    field_assignments {
      field_name: "arithmetic_power_2"
      no_aggregation { expression_node_index: 22 }
    }
    field_assignments {
      field_name: "arithmetic_power_1_5"
      no_aggregation { expression_node_index: 24 }
    }
    field_assignments {
      field_name: "arithmetic_power_minus_1"
      no_aggregation { expression_node_index: 26 }
    }
    field_assignments {
      field_name: "arithmetic_absolute_positive"
      no_aggregation { expression_node_index: 27 }
    }
    field_assignments {
      field_name: "arithmetic_absolute_negative"
      no_aggregation { expression_node_index: 28 }
    }
  }
}
