# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

uuid: "f630897c-44c3-48c1-be0f-2f76d12398f5"
version: 3758096386
descriptor_protos {
  name: "adhoc.proto"
  package: "aaos.sdv.telemetry.adhoc"
  message_type {
    name: "aggregation_publisher"
    field { name: "value" number: 1 type: TYPE_INT32 }
  }
  message_type {
    name: "on_aggregation_publisher"
    field { name: "value" number: 1 type: TYPE_INT32 }
  }
  message_type {
    name: "on_conditional_trigger"
    field { name: "value" number: 1 type: TYPE_INT32 }
  }
  message_type {
    name: "on_start_trigger"
    field { name: "value" number: 1 type: TYPE_INT32 }
  }
  syntax: "proto2"
}
triggers {
  name: "conditional_trigger"
  conditional_trigger {
    trigger_names: "start_trigger"
    selector_node_index: 0
    is_true {}
  }
}
triggers {
  name: "data_trigger"
  data_trigger { publisher_name: "aggregation_publisher" }
}
triggers {
  name: "finish_trigger"
  periodic_trigger { interval { nanos: 150000000 } }
}
triggers {
  name: "start_trigger"
  periodic_trigger { interval { nanos: 100000000 } }
}
publishers {
  name: "aggregation_publisher"
  aggregation_publisher {
    trigger_names: "start_trigger"
    message_builder {
      message_type: ".aaos.sdv.telemetry.adhoc.aggregation_publisher"
      field_assignments {
        field_name: "value"
        no_aggregation { expression_node_index: 1 }
      }
    }
  }
}
# Expression Node 0
expression_nodes { constant_leaf_node { bool_value: true } }
# Expression Node 1
expression_nodes { constant_leaf_node { int32_value: 42 } }
metrics_report_configs {
  name: "on_aggregation_publisher"
  trigger_names: "data_trigger"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.on_aggregation_publisher"
    field_assignments {
      field_name: "value"
      no_aggregation { expression_node_index: 1 }
    }
  }
}
metrics_report_configs {
  name: "on_conditional_trigger"
  trigger_names: "conditional_trigger"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.on_conditional_trigger"
    field_assignments {
      field_name: "value"
      no_aggregation { expression_node_index: 1 }
    }
  }
}
metrics_report_configs {
  name: "on_start_trigger"
  trigger_names: "start_trigger"
  message_builder {
    message_type: ".aaos.sdv.telemetry.adhoc.on_start_trigger"
    field_assignments {
      field_name: "value"
      no_aggregation { expression_node_index: 1 }
    }
  }
}
start_trigger_name: "start_trigger"
finish_trigger_name: "finish_trigger"
