# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

service_name: ".mcg.test.car_speed_msg"
data_format_protos {
  name: "specific_speed.proto"
  package: "mcg.test"
  message_type {
    name: "car_speed_msg"
    field { name: "speed" number: 1 type: TYPE_DOUBLE json_name: "speed" }
    field {
      name: "unit"
      number: 2
      type: TYPE_ENUM
      json_name: "unit"
      type_name: ".mcg.test.Unit"

    }
    field { name: "sample_int" number: 3 type: TYPE_INT32 json_name: "sample_int" }
    field { name: "sample_float" number: 4 type: TYPE_FLOAT json_name: "sample_float" }
  }

  enum_type {
    name: "Unit"
    value { name: "METRIC" number: 0 }
    value { name: "IMPERIAL" number: 1 }
    value { name: "RPM" number: 2 }
  }
}
data_format_message_name: ".mcg.test.car_speed_msg"
data_generators {
  loop_data: false
  default_delay { seconds: 1 nanos: 0 }
  csv_file { file_path: "/data/local/tmp/speed_publisher_data.csv" delimiter: "," }
}
