# Copyright 2025 Google LLC
#
# Trace configuration for Perfetto capture.
# You can use Perfetto UI to generate a config at https://ui.perfetto.dev/#!/record/instructions
# Documentation: https://perfetto.dev/docs/concepts/config
# Reference: https://perfetto.dev/docs/reference/trace-config-proto
# Example configs: https://cs.android.com/android/platform/superproject/+/master:external/perfetto/test/configs/

# The duration of the trace.
# duration_ms: 15000

# google3/java/com/google/devtools/hawkeye/measurer/perfetto/trace_config.textproto
# periodically writes the trace to disk.
 write_into_file: true
 file_write_period_ms: 3000

 flush_period_ms: 5000


# If data sources are writing at different rates, it may be beneficial to direct them to different
# buffers. The target_buffer property of a source config determines the used buffer.
# Here we define a second smaller buffer for infrequent sources.
buffers: {
    # Buffer #0
    size_kb: 32768
    fill_policy: RING_BUFFER
}
buffers {
  # Buffer #1
  size_kb: 32768
  fill_policy: RING_BUFFER
}

data_sources: {
    config {
        # Process stats help Perfetto with thread grouping and process names.
        # Config reference: https://perfetto.dev/docs/reference/trace-config-proto#ProcessStatsConfig
        name: "linux.process_stats"
        target_buffer: 0
        process_stats_config {
            scan_all_processes_on_start: true

            # Intervals to collect memory stat counters. Use interval >100 ms to not load CPU.
            # Doc: https://perfetto.dev/docs/data-sources/memory-counters#per-process-polled-counters
            # Uncomment to enable.
            proc_stats_poll_ms: 1000
        }
    }
}

# heapprofd_config is high frequency, so it gets its own buffer.
data_sources: {
    config {
        name: "android.heapprofd"
        target_buffer: 1
        heapprofd_config {
            sampling_interval_bytes: 16384
            process_cmdline: "ServiceBundleFoo:instance"
            process_cmdline: "ServiceBundleQux:instance"
            process_cmdline: "sdv_sd_agent"
            process_cmdline: "sdv_lifecycle_agent"
            process_cmdline: "dt_agent"
            process_cmdline: "rpcagent"

            shmem_size_bytes: 4194304
            #block_client: true

            #Profile all processes eligible for profiling on the system, not recommended
            #all: true
            all_heaps: false
            # Continuously dump profiles to see changes over time
            continuous_dump_config {
                dump_phase_ms: 5000 # Dump every 5 seconds
            }

        }
    }
}
data_sources: {
    config {
        name: "linux.system_info"
        target_buffer: 0
    }
}

data_sources: {
    config {
        # /proc counters.
        # Config reference: https://perfetto.dev/docs/reference/trace-config-proto#SysStatsConfig
        name: "linux.sys_stats"
        target_buffer: 0
        sys_stats_config {
            meminfo_period_ms: 1000
            meminfo_counters: MEMINFO_MEM_TOTAL
            meminfo_counters: MEMINFO_ACTIVE_ANON
            meminfo_counters: MEMINFO_ACTIVE_FILE
            meminfo_counters: MEMINFO_INACTIVE_ANON
            meminfo_counters: MEMINFO_INACTIVE_FILE
            meminfo_counters: MEMINFO_KERNEL_STACK
            meminfo_counters: MEMINFO_MLOCKED
            meminfo_counters: MEMINFO_SHMEM
            meminfo_counters: MEMINFO_SLAB
            meminfo_counters: MEMINFO_SLAB_UNRECLAIMABLE
            meminfo_counters: MEMINFO_VMALLOC_USED
            meminfo_counters: MEMINFO_MEM_FREE
            meminfo_counters: MEMINFO_SWAP_FREE

            vmstat_period_ms: 1000
            vmstat_counters: VMSTAT_PGFAULT
            vmstat_counters: VMSTAT_PGMAJFAULT
            vmstat_counters: VMSTAT_PGFREE
            vmstat_counters: VMSTAT_PGPGIN
            vmstat_counters: VMSTAT_PGPGOUT
            vmstat_counters: VMSTAT_PSWPIN
            vmstat_counters: VMSTAT_PSWPOUT
            vmstat_counters: VMSTAT_PGSCAN_DIRECT
            vmstat_counters: VMSTAT_PGSTEAL_DIRECT
            vmstat_counters: VMSTAT_PGSCAN_KSWAPD
            vmstat_counters: VMSTAT_PGSTEAL_KSWAPD
            vmstat_counters: VMSTAT_WORKINGSET_REFAULT
        }
    }
}

data_sources: {
    config {
        # Kernel tracing info.
        # Config reference: https://perfetto.dev/docs/reference/trace-config-proto#FtraceConfig
        name: "linux.ftrace"
        ftrace_config {
            # Doc: https://perfetto.dev/docs/case-studies/memory#lmk
            ftrace_events: "lowmemorykiller/lowmemory_kill"
            ftrace_events: "oom/oom_score_adj_update"
            ftrace_events: "ftrace/print"
            atrace_apps: "lmkd"

            # App events are those that use the app tag in ATrace (ATRACE_TAG_APP).
            # The app tag is the same for all apps and the events are enabled based on the app name.
            # Setting atrace_apps to "*" enable ATrace events for all apps. Setting it to app name
            # restricts them to those apps. Use multiple atrace_apps entries to enable multiple apps.
            # atrace_apps: "*"

             preserve_ftrace_buffer: true
        }
    }
}
