# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
uuid: "aa27583c-96a5-4a67-adad-d15e00c0f12a"
version: 1

descriptor_protos {
  message_type {
    name: "Report"
    field { type: TYPE_DOUBLE name: "speed" label: LABEL_OPTIONAL number: 1 }
  }
}

publishers {
  name: "speed_publisher"
  service_publisher {
    service_name: "com.google.sdv.telemetry.samples.DataTunnelPublisherSpeed#"
                  "Speed"
  }
}

triggers {
  name: "report_trigger"
  data_trigger { publisher_name: "speed_publisher" }
}

# index 0
expression_nodes { field_leaf_node { publisher_name: "speed_publisher" field_names: "speed" } }

metrics_report_configs {
  name: "speed"
  trigger_names: "report_trigger"
  report_incomplete: false

  message_builder {
    message_type: ".Report"
    field_assignments {
      field_name: "speed"
      no_aggregation { expression_node_index: 0 }
    }
  }
}
