# Copyright 2025 Google LLC

TestBeds:
  - Name: OneDeviceTestBed
    Controllers:
      AndroidDevice:
        - serial: serial_number
          label: device1
    TestParams:
      number_of_devices: 1