# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests that libsdv_dump behaves as expected: creates binder interface,
outputs report generated by DumpStateReporters via dumpsys mechanism"""

from mobly import asserts
import logging

from sdv_test_fw.test_execution import sdv_base_test, sdv_test_runner


class SdvAgentDumpBinderTests(sdv_base_test.SdvBaseTestClass):
    def setup_class(self):
        super().setup_class()
        self.sdv_device = self.get_device('device1').adb()
        self.sdv_device.root_device()

    def test_lib_sdv_dump_standalone_with_sample(self):
        logging.info("Starting test_lib_sdv_dump_standalone_with_sample")

        command = "com.sdv.google.sample.testing.sdv_dump"
        subprocess_name = "sdv_dump_test_binary_process"
        self.sdv_device.execute_shell_command_in_subprocess(
            subprocess_name, command)

        report = self.sdv_device.dumpsys(
            "com.google.sdv.ISdvAgent/sdvdump_e2e_test")

        expected_1 = "Binder used for libsdv_dump e2e testing"
        expected_2 = "My state: true"

        asserts.assert_in(
            expected_1, report,
            f'Did not find expected string:"{expected_1}" in dumpsys: {report}')
        asserts.assert_in(
            expected_2, report,
            f'Did not find expected string:"{expected_2}" in dumpsys: {report}')

        logging.info("Finished")


if __name__ == '__main__':
    # Start Test Execution Using SDV Test Framework
    sdv_test_runner.run()
