// Copyright (C) 2025 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package har.vehicledata.grpc;

import "vehicledata.proto";
import "vehicle_tire.proto";

// Contains the response code for a PublishRequest.
enum PublishVehicleDataResponseStatus {
    STATUS_UNKNOWN = 0;
    STATUS_OK = 1;
    STATUS_SDV_ERROR = 2;
    STATUS_NOT_DELIVERED = 3;
    STATUS_PROTOCOL_ERROR = 4;
}

message PublishVehicleDataResponse {
    PublishVehicleDataResponseStatus status = 1;
}

message PublishVehicleSpeedRequest {
    VehicleSpeedTopic topic = 1;
    VehicleSpeed speed = 2;
}

message PublishTelltaleStatusRequest {
    Telltale topic = 1;
    TellTaleStatus status = 2;
}

message PublishCurrentGearRequest {
    CurrentGearTopic topic = 1;
    CurrentGear gear = 2;
}

message PublishTirePressureRequest {
    Location topic = 1;
    TirePressure pressure = 2;
}

message PublishEngineRpmRequest {
    EngineRpmTopic topic = 1;
    EngineRpm rpm = 2;
}

service SdvVehicleDataGrpc {
  // Publishes a vehicle speed update.
  rpc PublishVehicleSpeed(PublishVehicleSpeedRequest) returns (PublishVehicleDataResponse) {}
  // Publishes a telltale status update.
  rpc PublishTelltaleStatus(PublishTelltaleStatusRequest) returns (PublishVehicleDataResponse) {}
  // Publishes a current gear update.
  rpc PublishCurrentGear(PublishCurrentGearRequest) returns (PublishVehicleDataResponse) {}
  // Publishes a tire pressure update.
  rpc PublishTirePressure(PublishTirePressureRequest) returns (PublishVehicleDataResponse) {}
  // Publishes an engine RPM update.
  rpc PublishEngineRpm(PublishEngineRpmRequest) returns (PublishVehicleDataResponse) {}
}