// Copyright (C) 2025 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// TODO(335314414): Remove this file and use vehicledata/sdv_vehicledata_catalog/vehicledata.proto

syntax = "proto3";

package har.vehicledata;

enum VehicleSpeedTopic {
    VEHICLE_SPEED = 0;
    MAX_SPEED = 1;
    SPEEDLIMIT = 2;
}

message VehicleSpeed {
    uint32 speed = 1;
    float precise_speed = 2;
}

// Alert type telltales
enum Telltale {
    OIL_PRESSURE = 0;
    ENGINE_TEMP = 1;
    CHECK_ENGINE = 2;
    CHARGING_FAILURE = 3;
    SEATBELT_DRIVER = 4;
    SEATBELT_PASSENGER = 5;
    LOW_TIRE_PRESSURE = 6;
    AIRBAG = 7;
    ABS = 8;
    BRAKE = 9;
    TRACTION = 10;
    FOG_LIGHTS = 11;
    PARK_LIGHTS = 12;
    HIBEAM = 13;
    LOWBEAM = 14;
    TURN_SIGNAL_LEFT = 15;
    TURN_SIGNAL_RIGHT = 16;
    ADAS = 17;
    MAX_SPEED_DISPLAYED = 18;
    SPEED_LIMIT_DISPLAYED = 20;
    EMERGENCY_LIGHT = 22;
}

message TellTaleStatus {
  bool alert = 1;
}

enum Gear {
    P = 0;
    R = 1;
    N = 2;
    D = 3;
}

enum CurrentGearTopic {
   GEAR = 0;
}

message CurrentGear {
    Gear gear = 1;
}

// RPM
enum EngineRpmTopic {
    ENGINE_RPM = 0;
}

message EngineRpm {
    uint32 rpm = 1;
}
